import type { WeatherData } from "./types";

export const CITIES_DATA: WeatherData[] = [
  {
    id: "madrid",
    location: { city: "Madrid", country: "España" },
    current: {
      temperature: 28,
      humidity: 30,
      pressure: 1012,
      windSpeed: 15,
      description: "soleado",
    },
    hourly: [
      { time: "14:00", temperature: 28, description: "soleado" },
      { time: "15:00", temperature: 29, description: "soleado" },
      { time: "16:00", temperature: 29, description: "soleado" },
      { time: "17:00", temperature: 28, description: "soleado" },
      { time: "18:00", temperature: 27, description: "despejado" },
      { time: "19:00", temperature: 26, description: "despejado" },
      { time: "20:00", temperature: 24, description: "despejado" },
      { time: "21:00", temperature: 22, description: "despejado" },
    ],
    daily: [
      { day: "Hoy", high: 30, low: 18, description: "soleado" },
      { day: "Lun", high: 31, low: 19, description: "soleado" },
      { day: "Mar", high: 29, low: 17, description: "parcialmente nublado" },
      { day: "Mié", high: 27, low: 16, description: "lluvia ligera" },
      { day: "Jue", high: 28, low: 16, description: "parcialmente nublado" },
      { day: "Vie", high: 30, low: 18, description: "soleado" },
      { day: "Sáb", high: 32, low: 20, description: "soleado" },
    ],
    history: [
      { date: "Hace 7 días", avgTemp: 24 },
      { date: "Hace 6 días", avgTemp: 25 },
      { date: "Hace 5 días", avgTemp: 23 },
      { date: "Hace 4 días", avgTemp: 26 },
      { date: "Hace 3 días", avgTemp: 27 },
      { date: "Hace 2 días", avgTemp: 26 },
      { date: "Ayer", avgTemp: 25 },
    ],
  },
  {
    id: "buenos-aires",
    location: { city: "Buenos Aires", country: "Argentina" },
    current: {
      temperature: 15,
      humidity: 80,
      pressure: 1018,
      windSpeed: 20,
      description: "nublado",
    },
    hourly: [
      { time: "14:00", temperature: 15, description: "nublado" },
      { time: "15:00", temperature: 16, description: "nublado" },
      { time: "16:00", temperature: 16, description: "lluvia ligera" },
      { time: "17:00", temperature: 15, description: "lluvia ligera" },
      { time: "18:00", temperature: 14, description: "nublado" },
      { time: "19:00", temperature: 13, description: "nublado" },
      { time: "20:00", temperature: 12, description: "parcialmente nublado" },
      { time: "21:00", temperature: 11, description: "parcialmente nublado" },
    ],
    daily: [
      { day: "Hoy", high: 17, low: 10, description: "nublado" },
      { day: "Lun", high: 18, low: 11, description: "chubascos" },
      { day: "Mar", high: 19, low: 12, description: "parcialmente nublado" },
      { day: "Mié", high: 20, low: 13, description: "soleado" },
      { day: "Jue", high: 21, low: 14, description: "soleado" },
      { day: "Vie", high: 19, low: 12, description: "parcialmente nublado" },
      { day: "Sáb", high: 18, low: 11, description: "nublado" },
    ],
    history: [
        { date: "Hace 7 días", avgTemp: 14 },
        { date: "Hace 6 días", avgTemp: 13 },
        { date: "Hace 5 días", avgTemp: 15 },
        { date: "Hace 4 días", avgTemp: 16 },
        { date: "Hace 3 días", avgTemp: 17 },
        { date: "Hace 2 días", avgTemp: 16 },
        { date: "Ayer", avgTemp: 15 },
    ],
  },
  {
    id: "mexico-city",
    location: { city: "Ciudad de México", country: "México" },
    current: {
      temperature: 22,
      humidity: 65,
      pressure: 1020,
      windSpeed: 10,
      description: "tormentas",
    },
    hourly: [
      { time: "14:00", temperature: 22, description: "parcialmente nublado" },
      { time: "15:00", temperature: 23, description: "parcialmente nublado" },
      { time: "16:00", temperature: 23, description: "tormentas" },
      { time: "17:00", temperature: 22, description: "tormentas" },
      { time: "18:00", temperature: 21, description: "chubascos" },
      { time: "19:00", temperature: 20, description: "chubascos" },
      { time: "20:00", temperature: 19, description: "parcialmente nublado" },
      { time: "21:00", temperature: 18, description: "parcialmente nublado" },
    ],
    daily: [
      { day: "Hoy", high: 24, low: 14, description: "tormentas" },
      { day: "Lun", high: 25, low: 15, description: "tormentas" },
      { day: "Mar", high: 24, low: 14, description: "chubascos" },
      { day: "Mié", high: 26, low: 16, description: "parcialmente nublado" },
      { day: "Jue", high: 27, low: 17, description: "parcialmente nublado" },
      { day: "Vie", high: 26, low: 16, description: "chubascos" },
      { day: "Sáb", high: 25, low: 15, description: "tormentas" },
    ],
    history: [
        { date: "Hace 7 días", avgTemp: 21 },
        { date: "Hace 6 días", avgTemp: 20 },
        { date: "Hace 5 días", avgTemp: 22 },
        { date: "Hace 4 días", avgTemp: 23 },
        { date: "Hace 3 días", avgTemp: 22 },
        { date: "Hace 2 días", avgTemp: 21 },
        { date: "Ayer", avgTemp: 22 },
    ],
  },
];
