import type { WeatherData } from "./types";
import { format } from "date-fns";
import { es } from "date-fns/locale";

const today = new Date();
const getFutureDate = (days: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + days);
  return date;
};

const getDayName = (date: Date) => {
  return format(date, "EEE", { locale: es });
};

export const CITIES_DATA: WeatherData[] = [
  {
    id: "madrid",
    location: { city: "Madrid", country: "España", timeZone: "Europe/Madrid" },
    current: {
      temperature: 28,
      feelsLike: 29,
      humidity: 30,
      pressure: 1012,
      windSpeed: 15,
      windDirection: "SO",
      uvIndex: 8,
      dewPoint: 9,
      visibility: 10,
      sunrise: "06:45",
      sunset: "21:30",
      description: "soleado",
    },
    hourly: [
      { time: "14:00", temperature: 28, description: "soleado", precipitationChance: 0, windSpeed: 15 },
      { time: "15:00", temperature: 29, description: "soleado", precipitationChance: 0, windSpeed: 16 },
      { time: "16:00", temperature: 29, description: "soleado", precipitationChance: 5, windSpeed: 14 },
      { time: "17:00", temperature: 28, description: "soleado", precipitationChance: 5, windSpeed: 13 },
      { time: "18:00", temperature: 27, description: "despejado", precipitationChance: 0, windSpeed: 12 },
      { time: "19:00", temperature: 26, description: "despejado", precipitationChance: 0, windSpeed: 10 },
      { time: "20:00", temperature: 24, description: "despejado", precipitationChance: 0, windSpeed: 9 },
      { time: "21:00", temperature: 22, description: "despejado", precipitationChance: 0, windSpeed: 8 },
    ],
    daily: [
      { day: "Hoy", high: 30, low: 18, description: "soleado", precipitationChance: 5, date: getFutureDate(0) },
      { day: getDayName(getFutureDate(1)), high: 31, low: 19, description: "soleado", precipitationChance: 10, date: getFutureDate(1) },
      { day: getDayName(getFutureDate(2)), high: 29, low: 17, description: "parcialmente nublado", precipitationChance: 20, date: getFutureDate(2) },
      { day: getDayName(getFutureDate(3)), high: 27, low: 16, description: "lluvia ligera", precipitationChance: 60, date: getFutureDate(3) },
      { day: getDayName(getFutureDate(4)), high: 28, low: 16, description: "parcialmente nublado", precipitationChance: 25, date: getFutureDate(4) },
      { day: getDayName(getFutureDate(5)), high: 30, low: 18, description: "soleado", precipitationChance: 10, date: getFutureDate(5) },
      { day: getDayName(getFutureDate(6)), high: 32, low: 20, description: "soleado", precipitationChance: 5, date: getFutureDate(6) },
    ],
    history: [
      { date: "Hace 7 días", avgTemp: 24 },
      { date: "Hace 6 días", avgTemp: 25 },
      { date: "Hace 5 días", avgTemp: 23 },
      { date: "Hace 4 días", avgTemp: 26 },
      { date: "Hace 3 días", avgTemp: 27 },
      { date: "Hace 2 días", avgTemp: 26 },
      { date: "Ayer", avgTemp: 25 },
    ],
  },
  {
    id: "buenos-aires",
    location: { city: "Buenos Aires", country: "Argentina", timeZone: "America/Argentina/Buenos_Aires" },
    current: {
      temperature: 15,
      feelsLike: 13,
      humidity: 80,
      pressure: 1018,
      windSpeed: 20,
      windDirection: "SE",
      uvIndex: 2,
      dewPoint: 12,
      visibility: 8,
      sunrise: "07:35",
      sunset: "18:10",
      description: "nublado",
    },
    hourly: [
      { time: "14:00", temperature: 15, description: "nublado", precipitationChance: 40, windSpeed: 20 },
      { time: "15:00", temperature: 16, description: "nublado", precipitationChance: 45, windSpeed: 22 },
      { time: "16:00", temperature: 16, description: "lluvia ligera", precipitationChance: 60, windSpeed: 25 },
      { time: "17:00", temperature: 15, description: "lluvia ligera", precipitationChance: 65, windSpeed: 24 },
      { time: "18:00", temperature: 14, description: "nublado", precipitationChance: 50, windSpeed: 20 },
      { time: "19:00", temperature: 13, description: "nublado", precipitationChance: 40, windSpeed: 18 },
      { time: "20:00", temperature: 12, description: "parcialmente nublado", precipitationChance: 30, windSpeed: 15 },
      { time: "21:00", temperature: 11, description: "parcialmente nublado", precipitationChance: 25, windSpeed: 14 },
    ],
    daily: [
      { day: "Hoy", high: 17, low: 10, description: "nublado", precipitationChance: 50, date: getFutureDate(0) },
      { day: getDayName(getFutureDate(1)), high: 18, low: 11, description: "chubascos", precipitationChance: 70, date: getFutureDate(1) },
      { day: getDayName(getFutureDate(2)), high: 19, low: 12, description: "parcialmente nublado", precipitationChance: 30, date: getFutureDate(2) },
      { day: getDayName(getFutureDate(3)), high: 20, low: 13, description: "soleado", precipitationChance: 10, date: getFutureDate(3) },
      { day: getDayName(getFutureDate(4)), high: 21, low: 14, description: "soleado", precipitationChance: 5, date: getFutureDate(4) },
      { day: getDayName(getFutureDate(5)), high: 19, low: 12, description: "parcialmente nublado", precipitationChance: 20, date: getFutureDate(5) },
      { day: getDayName(getFutureDate(6)), high: 18, low: 11, description: "nublado", precipitationChance: 40, date: getFutureDate(6) },
    ],
    history: [
        { date: "Hace 7 días", avgTemp: 14 },
        { date: "Hace 6 días", avgTemp: 13 },
        { date: "Hace 5 días", avgTemp: 15 },
        { date: "Hace 4 días", avgTemp: 16 },
        { date: "Hace 3 días", avgTemp: 17 },
        { date: "Hace 2 días", avgTemp: 16 },
        { date: "Ayer", avgTemp: 15 },
    ],
  },
  {
    id: "mexico-city",
    location: { city: "Ciudad de México", country: "México", timeZone: "America/Mexico_City" },
    current: {
      temperature: 22,
      feelsLike: 22,
      humidity: 65,
      pressure: 1020,
      windSpeed: 10,
      windDirection: "N",
      uvIndex: 11,
      dewPoint: 15,
      visibility: 9,
      sunrise: "06:10",
      sunset: "19:45",
      description: "tormentas",
    },
    hourly: [
      { time: "14:00", temperature: 22, description: "parcialmente nublado", precipitationChance: 30, windSpeed: 10 },
      { time: "15:00", temperature: 23, description: "parcialmente nublado", precipitationChance: 40, windSpeed: 12 },
      { time: "16:00", temperature: 23, description: "tormentas", precipitationChance: 80, windSpeed: 15 },
      { time: "17:00", temperature: 22, description: "tormentas", precipitationChance: 85, windSpeed: 14 },
      { time: "18:00", temperature: 21, description: "chubascos", precipitationChance: 70, windSpeed: 10 },
      { time: "19:00", temperature: 20, description: "chubascos", precipitationChance: 60, windSpeed: 8 },
      { time: "20:00", temperature: 19, description: "parcialmente nublado", precipitationChance: 40, windSpeed: 7 },
      { time: "21:00", temperature: 18, description: "parcialmente nublado", precipitationChance: 30, windSpeed: 6 },
    ],
    daily: [
      { day: "Hoy", high: 24, low: 14, description: "tormentas", precipitationChance: 80, date: getFutureDate(0) },
      { day: getDayName(getFutureDate(1)), high: 25, low: 15, description: "tormentas", precipitationChance: 85, date: getFutureDate(1) },
      { day: getDayName(getFutureDate(2)), high: 24, low: 14, description: "chubascos", precipitationChance: 70, date: getFutureDate(2) },
      { day: getDayName(getFutureDate(3)), high: 26, low: 16, description: "parcialmente nublado", precipitationChance: 30, date: getFutureDate(3) },
      { day: getDayName(getFutureDate(4)), high: 27, low: 17, description: "parcialmente nublado", precipitationChance: 25, date: getFutureDate(4) },
      { day: getDayName(getFutureDate(5)), high: 26, low: 16, description: "chubascos", precipitationChance: 60, date: getFutureDate(5) },
      { day: getDayName(getFutureDate(6)), high: 25, low: 15, description: "tormentas", precipitationChance: 75, date: getFutureDate(6) },
    ],
    history: [
        { date: "Hace 7 días", avgTemp: 21 },
        { date: "Hace 6 días", avgTemp: 20 },
        { date: "Hace 5 días", avgTemp: 22 },
        { date: "Hace 4 días", avgTemp: 23 },
        { date: "Hace 3 días", avgTemp: 22 },
        { date: "Hace 2 días", avgTemp: 21 },
        { date: "Ayer", avgTemp: 22 },
    ],
  },
  {
    id: "tokyo",
    location: { city: "Tokio", country: "Japón", timeZone: "Asia/Tokyo" },
    current: {
      temperature: 26,
      feelsLike: 28,
      humidity: 75,
      pressure: 1010,
      windSpeed: 12,
      windDirection: "E",
      uvIndex: 7,
      dewPoint: 21,
      visibility: 10,
      sunrise: "04:30",
      sunset: "19:00",
      description: "parcialmente nublado",
    },
    hourly: [
      { time: "09:00", temperature: 26, description: "parcialmente nublado", precipitationChance: 20, windSpeed: 12 },
      { time: "10:00", temperature: 27, description: "parcialmente nublado", precipitationChance: 15, windSpeed: 13 },
      { time: "11:00", temperature: 28, description: "soleado", precipitationChance: 10, windSpeed: 14 },
      { time: "12:00", temperature: 29, description: "soleado", precipitationChance: 5, windSpeed: 15 },
      { time: "13:00", temperature: 30, description: "soleado", precipitationChance: 5, windSpeed: 14 },
      { time: "14:00", temperature: 30, description: "soleado", precipitationChance: 10, windSpeed: 13 },
      { time: "15:00", temperature: 29, description: "parcialmente nublado", precipitationChance: 15, windSpeed: 12 },
      { time: "16:00", temperature: 28, description: "parcialmente nublado", precipitationChance: 20, windSpeed: 11 },
    ],
    daily: [
      { day: "Hoy", high: 30, low: 24, description: "parcialmente nublado", precipitationChance: 20, date: getFutureDate(0) },
      { day: getDayName(getFutureDate(1)), high: 31, low: 25, description: "chubascos", precipitationChance: 60, date: getFutureDate(1) },
      { day: getDayName(getFutureDate(2)), high: 29, low: 24, description: "soleado", precipitationChance: 10, date: getFutureDate(2) },
      { day: getDayName(getFutureDate(3)), high: 32, low: 26, description: "soleado", precipitationChance: 5, date: getFutureDate(3) },
      { day: getDayName(getFutureDate(4)), high: 31, low: 25, description: "parcialmente nublado", precipitationChance: 30, date: getFutureDate(4) },
      { day: getDayName(getFutureDate(5)), high: 30, low: 24, description: "parcialmente nublado", precipitationChance: 40, date: getFutureDate(5) },
      { day: getDayName(getFutureDate(6)), high: 29, low: 23, description: "chubascos", precipitationChance: 70, date: getFutureDate(6) },
    ],
    history: [
      { date: "Hace 7 días", avgTemp: 27 },
      { date: "Hace 6 días", avgTemp: 28 },
      { date: "Hace 5 días", avgTemp: 26 },
      { date: "Hace 4 días", avgTemp: 29 },
      { date: "Hace 3 días", avgTemp: 28 },
      { date: "Hace 2 días", avgTemp: 27 },
      { date: "Ayer", avgTemp: 28 },
    ],
  },
  {
    id: "paris",
    location: { city: "París", country: "Francia", timeZone: "Europe/Paris" },
    current: {
      temperature: 22,
      feelsLike: 22,
      humidity: 55,
      pressure: 1015,
      windSpeed: 18,
      windDirection: "O",
      uvIndex: 6,
      dewPoint: 12,
      visibility: 10,
      sunrise: "05:50",
      sunset: "21:55",
      description: "soleado",
    },
    hourly: [
      { time: "13:00", temperature: 22, description: "soleado", precipitationChance: 5, windSpeed: 18 },
      { time: "14:00", temperature: 23, description: "soleado", precipitationChance: 5, windSpeed: 19 },
      { time: "15:00", temperature: 24, description: "soleado", precipitationChance: 10, windSpeed: 20 },
      { time: "16:00", temperature: 24, description: "parcialmente nublado", precipitationChance: 15, windSpeed: 18 },
      { time: "17:00", temperature: 23, description: "parcialmente nublado", precipitationChance: 15, windSpeed: 17 },
      { time: "18:00", temperature: 22, description: "parcialmente nublado", precipitationChance: 10, windSpeed: 15 },
      { time: "19:00", temperature: 21, description: "despejado", precipitationChance: 5, windSpeed: 14 },
      { time: "20:00", temperature: 20, description: "despejado", precipitationChance: 0, windSpeed: 12 },
    ],
    daily: [
      { day: "Hoy", high: 24, low: 15, description: "soleado", precipitationChance: 10, date: getFutureDate(0) },
      { day: getDayName(getFutureDate(1)), high: 25, low: 16, description: "soleado", precipitationChance: 5, date: getFutureDate(1) },
      { day: getDayName(getFutureDate(2)), high: 23, low: 14, description: "parcialmente nublado", precipitationChance: 20, date: getFutureDate(2) },
      { day: getDayName(getFutureDate(3)), high: 21, low: 13, description: "lluvia ligera", precipitationChance: 50, date: getFutureDate(3) },
      { day: getDayName(getFutureDate(4)), high: 22, low: 14, description: "parcialmente nublado", precipitationChance: 25, date: getFutureDate(4) },
      { day: getDayName(getFutureDate(5)), high: 24, low: 15, description: "soleado", precipitationChance: 10, date: getFutureDate(5) },
      { day: getDayName(getFutureDate(6)), high: 26, low: 17, description: "soleado", precipitationChance: 5, date: getFutureDate(6) },
    ],
    history: [
      { date: "Hace 7 días", avgTemp: 19 },
      { date: "Hace 6 días", avgTemp: 20 },
      { date: "Hace 5 días", avgTemp: 18 },
      { date: "Hace 4 días", avgTemp: 21 },
      { date: "Hace 3 días", avgTemp: 22 },
      { date: "Hace 2 días", avgTemp: 21 },
      { date: "Ayer", avgTemp: 20 },
    ],
  },
  {
    id: "sydney",
    location: { city: "Sídney", country: "Australia", timeZone: "Australia/Sydney" },
    current: {
      temperature: 18,
      feelsLike: 17,
      humidity: 60,
      pressure: 1022,
      windSpeed: 25,
      windDirection: "S",
      uvIndex: 4,
      dewPoint: 10,
      visibility: 10,
      sunrise: "06:30",
      sunset: "17:30",
      description: "parcialmente nublado",
    },
    hourly: [
      { time: "06:00", temperature: 16, description: "despejado", precipitationChance: 5, windSpeed: 15 },
      { time: "07:00", temperature: 17, description: "soleado", precipitationChance: 0, windSpeed: 18 },
      { time: "08:00", temperature: 18, description: "soleado", precipitationChance: 0, windSpeed: 20 },
      { time: "09:00", temperature: 20, description: "soleado", precipitationChance: 0, windSpeed: 22 },
      { time: "10:00", temperature: 21, description: "parcialmente nublado", precipitationChance: 10, windSpeed: 25 },
      { time: "11:00", temperature: 22, description: "parcialmente nublado", precipitationChance: 15, windSpeed: 24 },
      { time: "12:00", temperature: 22, description: "parcialmente nublado", precipitationChance: 15, windSpeed: 23 },
      { time: "13:00", temperature: 21, description: "parcialmente nublado", precipitationChance: 20, windSpeed: 22 },
    ],
    daily: [
      { day: "Hoy", high: 22, low: 15, description: "parcialmente nublado", precipitationChance: 20, date: getFutureDate(0) },
      { day: getDayName(getFutureDate(1)), high: 21, low: 14, description: "chubascos", precipitationChance: 60, date: getFutureDate(1) },
      { day: getDayName(getFutureDate(2)), high: 20, low: 13, description: "chubascos", precipitationChance: 70, date: getFutureDate(2) },
      { day: getDayName(getFutureDate(3)), high: 22, low: 14, description: "parcialmente nublado", precipitationChance: 30, date: getFutureDate(3) },
      { day: getDayName(getFutureDate(4)), high: 23, low: 15, description: "soleado", precipitationChance: 10, date: getFutureDate(4) },
      { day: getDayName(getFutureDate(5)), high: 24, low: 16, description: "soleado", precipitationChance: 5, date: getFutureDate(5) },
      { day: getDayName(getFutureDate(6)), high: 23, low: 15, description: "parcialmente nublado", precipitationChance: 15, date: getFutureDate(6) },
    ],
    history: [
      { date: "Hace 7 días", avgTemp: 18 },
      { date: "Hace 6 días", avgTemp: 19 },
      { date: "Hace 5 días", avgTemp: 17 },
      { date: "Hace 4 días", avgTemp: 20 },
      { date: "Hace 3 días", avgTemp: 21 },
      { date: "Hace 2 días", avgTemp: 20 },
      { date: "Ayer", avgTemp: 19 },
    ],
  },
];